league_oauth2_server:
    authorization_server:
        private_key: '%kernel.project_dir%/var/keys/private.key'
        private_key_passphrase: null
        encryption_key: def00000db0414c0c9779c851be6c780ae9d8c8ac1000fcc523c94564ceb48c93a440cc309d0955965cc1ddf7d80ece9ae0cf38d70a549a7cf3eb0dafcc3defcca6df539
        encryption_key_type: defuse
        access_token_ttl: PT1H
        refresh_token_ttl: P1M
        auth_code_ttl: PT10M
        enable_client_credentials_grant: true
        enable_password_grant: true
        enable_refresh_token_grant: true
        enable_auth_code_grant: true
        require_code_challenge_for_public_clients: false
        persist_access_token: true
    resource_server:
        public_key: '%kernel.project_dir%/var/keys/public.key'
    scopes:
        available:
            - PROFILE
            - MEDIA
            - BLOCK_READ
            - BLOCK_WRITE
        default:
            - BLOCK_READ
    persistence:
        doctrine:
            entity_manager: default
    role_prefix: ROLE_OAUTH2_
    client:
        classname: League\Bundle\OAuth2ServerBundle\Model\Client
